name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: dist/storybook
          build_command: npm run build-storybook
